name: Cypress Tests

env:
  browser: electron

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run --browser=$browser

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: yarn install
      
      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
        
  cypress-chrome-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: yarn install
      
      - name: Run E2E tests 
        env:
          browser: chrome
        run: ${{ github.event.inputs.cli }}
        
  cypress-firefox-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: yarn install
      
      - name: Run E2E tests 
        env:
          browser: firefox
        run: ${{ github.event.inputs.cli }}
